# Declarando el perfil que se usa en este entorno.
spring.profiles.active=dev

# Modificando el context path por donde se va a acceder a la app.
server.servlet.context-path=/cooperativebilling/api

#spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
