# Modificación del puerto por el que se ejecuta la app.(Default 8080)
server.port=8090

#Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/platzi-market
#spring.datasource.username=postgres
#spring.datasource.password=password

#spring.jpa.database=postgresql
